### PR TITLE
isPurchased -> true

### PR DESCRIPTION
**Pull request by xx-bean-xx**
fixes issue where users have to pay to use the app

### CODE REVIEW

**Comment by Wavesonics** [comment]
lol

**Comment by Wavesonics** [comment]
Does anyone even have a Pebble that still works? The company doesn't even exist anymore

**Comment by xx-bean-xx** [comment]
yeah, the community is still surprisingly alive. [Rebble](https://rebble.io/) is still around and their [Discord](https://discordapp.com/invite/aRUAYFN) is pretty active.

**Comment by ItsHarper** [comment]
@Wavesonics
Hi Adam, 

I just updated my fork of the app to update dependencies, work with recent versions of Android, and fix a few bugs. I did also remove billing support (the app isn't even listed on Google Play anymore, and re-listing it would require adding a foreground service, which it's nice to not need).

https://github.com/NoahAndrews/RingMyPhoneAndroid

My plan is to publish my fork to [F-Droid](https://f-droid.org/). Would you be willing to work with me to update the [Pebble app's page on the Rebble app directory](https://apps.rebble.io/en_US/application/52ed9b199755252f26000005?query=ringmyphone&section=watchapps) to make the Companion App link point to my fork on F-Droid?

Thanks for making the best find-my-Android-phone app for Pebble.

**Comment by Wavesonics** [comment]
It's incredible that people still use this!

I would be okay with merging your fixes and making this free now, how about submit a PR?

**Comment by ItsHarper** [comment]
Sure, we can do it that way. Thanks!

Because you don't even use this anymore, I took the liberty of doing things like reformatting the source code. I hope that's OK with you. GitHub's code review interface has the option to ignore whitespace changes, so that should help with the review process.

You'll need to log into the brand new [Rebble Dev Portal](https://dev-portal.rebble.io/), and claim the RingMyPhone Pebble app. Since you didn't migrate your Pebble account to Rebble back when the Pebble servers were still online, I'm not sure what that process will look like. It might be a manual review sort of thing. Once that's been claimed and F-Droid has built and published the app, you can update the Companion App link.

**Comment by ItsHarper** [comment]
Here are the details on the process of claiming the app entry: https://help.rebble.io/recover-developer-account/#1

**Comment by Wavesonics** [comment]
I will be back next week and can do this

**Pull request closed without merging**
